config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true,
                	length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def new
		@product = Product.new
	end

	def index
		@products = Product.all
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end

	def create 
		@product = Product.new(product_params)

		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def show 
		@product = Product.find(params[:id])
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :ref_pic)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdmunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Boogaloo' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
</head>
<body>
	<header class="fixed">
		<img src="img/1277739967961.jpg" id="logo"></img> 
		<div id="title-div">
			<h1 id="fixed-text"><a href="#">CrowdMunch!</a></h1>
		</div>
		<div id="bar-btns">
			<div id="home"><a href="">Home</a></div>
			<div id="how" ><a href="">How it works</a></div>
			<div id="contact"><a href="">Contact us!</a></div>
		</div>
		<form id="search-form">
			<label for="username"></label>
			<input type="text" name="search" id="search" value="Search!">
		</form>
	</header> 

<%= yield %>

<!-- scripts go here-->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript">
		$("#search").focus(function(){
			$search = $(this);
			$search.attr("value", "")
		}).blur(function(){
			$search = $(this);
			$search.attr("value", "Search!")
		});
	</script>
		<!-- HeadRoom direct plugin online from http://codeasp.net/blogs/raghav_khunger/microsoft-net/2314/how-to-use-headroom-js -->
		<style type="text/css">
		.headroom {position: fixed;top: 0;left: 0;right: 0;transition: all .3s ease-in-out;}
		.headroom--unpinned {top: -100px;}
		.headroom--pinned {top: 0;}
		</style>
		<script  type="text/javascript"  src="https://rawgithub.com/WickyNilliams/headroom.js/master/dist/headroom.js"></script>      
		<script  type="text/javascript"  src="https://rawgithub.com/WickyNilliams/headroom.js/master/src/jQuery.headroom.js"></script>
		<script type="text/javascript">
		$(".fixed").headroom();
		</script>
</body>
</html>

app/views/products/edit.html.erb
<h1>Editing product</h1>
 
<%= form_for :product, url: product_path(@product), method: :patch do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited
      this product from being saved:</h2>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :ref_pic %><br>
    <%= f.text_field :ref_pic, :value => "../assets/"  %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Destroy', product_path(@product),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<body>
  <!-- The old nav bar <div id="navigation-bar" class="">
    <nav>
      <div><a href="#">meats</a></div>
      <div><a href="#">veggies</a></div>
      <div><a href="#">fruits</a></div>
      <div><a href="#">dry goods</a></div>
      <div><a href="#">supplies</a></div>
      <div><a href="#">beverages</a></div>
      <div><a href="#">alcohol</a></div>
    </nav>
  </div> -->
  <!-- ##################
  This is the nav bar
  #################### -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">meats <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Beef</a></li>
                <li><a href="#">Chicken</a></li>
                <li><a href="#">Pork</a></li>
                <li><a href="#">Seafood</a></li>
                <li><a href="#">Specialty Cuts</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">veggies <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Local Veggies</a></li>
                <li><a href="#">Imported goods</a></li>
                <li class="divider"></li>
                <li>
                  <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button id="form-submit" type="submit" class="btn btn-default">Submit</button>
                  </form>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">fruits<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Local Produce</a></li>
                <li><a href="#">Imported Fruits</a></li>
                <li class="divider"></li>
                <li>
                  <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button id="form-submit" type="submit" class="btn btn-default">Submit</button>
                  </form>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">dry goods <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">supplies <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">beverages <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Soft Drinks</a></li>
                <li><a href="#">Juices</a></li>
                <li><a href="#">Water</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">alcohols <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Beers</a></li>
                <li><a href="#">Wines</a></li>
                <li><a href="#">Liquors</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<!-- GETTING STARTED ################################################
    <%= link_to 'Create a new product', new_product_path%>
    /GETTING STARTED ################################################-->
    <div class="buttons">
      <a class="twitter" href=""><img src="assets/twitter.png" /></a>
      <br>
      <a class="facebook" href=""><img src="assets/facebook.png" /></a>
      <br>
      <a class="dribble" href=""><img src="assets/dribble.png" /></a>
      <br>
      <a class="rss" href=""><img src="assets/rss.png" /></a>
    </div>


    <div id="wrapper" class="content">
      <h2 id="wrapper-header">Featured Products</h1>
        <% @products.each do |product| %>
        <div class="feature">
          <!-- featured pic wrapper div -->
          <div class="feature-pic-wrapper">
            <!-- <a href="<%= product.ref_pic %>">[name of picture]</a> -->
            <a href="#"><img id="feature-pic" src="<%= product.ref_pic %>"></a>
          </div>
          <div class="feature-info-section-wrapper">
            <div class="feature-title-wrapper">
              <a href="#"><h2 class="product-name"><%= product.name %></h2>
              </a>
            </div>
            <div class="feature-prog-bar-wrapper">
              <h6>Bulk progress!</h6>
              <!-- Prog-bar item -->
              <div class="prog-wrap">
                <div class="prog-bar"></div>
              </div>
            </div>
            <p class="product-description">
              <%= product.description %>
            </p>
          </div>
          <div class="feature-nav-links">
            <%= link_to 'Show', product_path(product) %>
            <%= link_to 'Edit', edit_product_path(product) %>
          </div>
        </div>
        <% end %>
      </div>
    </body>

app/views/products/new.html.erb
<h1>Create a new entry</h1>

<%= form_for :product, url: products_path do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@product.errors.count, "error") %> prohibited
		this product from being saved:</h2>
		<ul>
			<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :ref_pic %><br>
		<%= f.text_field :ref_pic, :value => "../assets/"  %>
	</p>

	<p>
		<%= f.submit %>
	</p>
	<% end %>
	<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
 
<img src="<%= @product.ref_pic %>">

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to "Back", products_path%>